name:                simple-chain
version:             0.1.0.0
github:              "danbroooks/simple-chain"
license:             BSD3
author:              "Dan Brooks"
maintainer:          ""
copyright:           "2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simple-chain#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  simple-chain-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-chain

tests:
  simple-chain-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-chain
